//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Comedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Empleados_Huellas
    {
        public int Huella_ID { get; set; }
        public string Empleado_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> No_Tarjeta { get; set; }
        public byte[] Huella_Digital { get; set; }
        public string Huella_Ruta { get; set; }
        public byte[] Imagen { get; set; }
    }
}
